---
grimoire:
  shortcuts:
    "grimoire": "grimoire"

  permissions:
    manage: manage_grimoire

  branches:
    ceremonial:
      name: "Ceremonial Magic"
      skill: "Ceremonial Magic"
    hedge:
      name: "Hedgecraft"
      skill: "Hedgecraft"
    forbidden:
      name: "Forbidden Magic"
      skill: "Forbidden Magic"

  jobs:
    spell_proposal_category: "Requests"

  casting:
    show_roll_details: true

  learning:
    xp_cost_per_skill_point: 1
